apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: frontend-app
spec:
  type: LoadBalancer  # Change to ClusterIP or NodePort if needed
  selector:
    app: frontend-app        # Must match your deployment's label
  ports:
    - protocol: TCP
      port: 80         # External port to expose
      targetPort: 80 # Port inside the container
