version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: cruduser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cruddb
    ports:
      - "5432:5432"
    networks:
      - backend_network

  backend:
    build: ./backend  # This assumes your backend is in the 'backend' folder
    environment:
      DB_HOST: postgres  # Use the service name defined above
      DB_USER: cruduser
      DB_PASSWORD: password
      DB_NAME: cruddb
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
