apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend-app
spec:
  type: LoadBalancer  # Change to ClusterIP or NodePort if needed
  selector:
    app: backend-app        # Must match your deployment's label
  ports:
    - protocol: TCP
      port: 5000         # External port to expose
      targetPort: 5000 # Port inside the container
