name: self-hosted for backend

on: 
  push: 
    branches: [ main ] 

jobs:
  build:
    runs-on: ubuntu-latest 

    strategy:
      matrix:
        python-version: 3.10

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        if ! command -v docker &> /dev/null; then
          echo "Installing Docker..."
          sudo apt update -y || sudo yum update -y
          sudo apt install -y docker.io || sudo yum install -y docker
          sudo systemctl start docker
          sudo systemctl enable docker
          sudo usermod -aG docker $USER
        else
          echo "Docker already installed"
        fi

      - name: Build Docker image
        run: | 
          docker build -t git-backend .

      - name: Stop old container if exists
      run: |
        docker stop git-backend-container || true
        docker rm git-backend-container || true

    - name: Run Flask c ontainer
      run: |
        docker run -d --name git-backend-container -p 5000:5000 \
          -e DB_NAME=cruddb \
          -e DB_USER=cruduser \
          -e DB_PASSWORD=password \
          -e DB_HOST=127.0.0.1 \
          git-backend

    - name: Upload logs
      uses: actions/upload-artifact@v3
      with:
        name: docker-logs
        path: /var/log/docker.log  # or replace with actual log/output files

