name: Build and push docker images to Artifact Registry

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build, Push, and Test with My SQL
    runs-on: self-hosted
    env:
      PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
      REPO_NAME: kuberepo
      BACKEND_IMAGE: asia-south1-docker.pkg.dev/chaithu-project-463807/kuberepo/backendkube:latest
      FRONTEND_IMAGE: asia-south1-docker.pkg.dev/chaithu-project-463807/kuberepo/frontendkube:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: chaithu-project-463807
          install_components: gke-gcloud-auth-plugin

          
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: authenticate gcp with remote
        run: gcloud config set project $PROJECT_ID

      - name: Configure Docker to use Artifact Registry
        run: gcloud auth configure-docker asia-south1-docker.pkg.dev

      - name: Who am I?
        run: gcloud auth list

      - name: Build Backend Docker Image
        run: docker build -t $BACKEND_IMAGE ./backend

      - name: Push Backend Image
        run: docker push $BACKEND_IMAGE

      - name: Build Frontend Docker Image
        run: docker build -t $FRONTEND_IMAGE ./frontend

      - name: Push Frontend Image
        run: docker push $FRONTEND_IMAGE
        
      - name: Authenticate to GKE
        run: |
          # gcloud components install gke-gcloud-auth-plugin
          gcloud container clusters get-credentials privatecluster --region asia-south1 --project $PROJECT_ID
      - name: Install kubectl
        run: |
          sudo apt-get update
          sudo apt-get install -y ca-certificates curl gnupg
          sudo mkdir -p /etc/apt/keyrings
          curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg |
          sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-archive-keyring.gpg

          # Add the Kubernetes apt repository
          echo "deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] \
          https://apt.kubernetes.io/ kubernetes main" |
          sudo tee /etc/apt/sources.list.d/kubernetes.list

          # Update and install
          sudo apt-get update
          sudo apt-get install -y kubectl


      - name: verifying kubectl
        run: |
          kubectl version
          kubectl get nodes
        
      - name: Deploy backend to GKE
        run: |
          kubectl apply -f ./backend/backdeploy.yml || true
          kubectl apply -f ./backend/backsvc.yaml || true  
          kubectl rollout restart deploy backend-app
      - name: Deploy frontend to GKE
        run: |
          kubectl apply -f ./frontend/frontdeploy.yml || true
          kubectl rollout restart deploy frontend-app
          kubectl apply -f ./frontend/frontsvc.yml || true

      - name: installing ingress controller
        run: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.10.1/deploy/static/provider/cloud/deploy.yaml

      - name: deploying ingress
        run: kubectl apply -f ingress.yaml
