name: self-hosted for backend

on: 
  push: 
    branches: [ main ] 

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: cruduser
          POSTGRES_PASSWORD: password
          POSTGRES_DB: cruddb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DB_HOST: localhost
      DB_PORT: 5432
      DB_NAME: cruddb
      DB_USER: cruduser
      DB_PASSWORD: password

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        if ! command -v docker &> /dev/null; then
          echo "Installing Docker..."
          sudo apt update -y || sudo yum update -y
          sudo apt install -y docker.io || sudo yum install -y docker
          sudo systemctl start docker
          sudo systemctl enable docker
          sudo usermod -aG docker $USER
        else
          echo "Docker already installed"
        fi

    - name: Build Docker image
      run: | 
          docker build -t git-backend ./backend

    - name: Stop old container if exists
      run: |
        docker stop git-backend-container || true
        docker rm git-backend-container || true

    - name: Wait for PostgreSQL to be ready
      run: |
        until pg_isready -h localhost -p 5432; do
          echo "Waiting for PostgreSQL to be ready..."
          sleep 2
        done

    - name: Run Flask c ontainer
      run: |
        docker run -d --name git-backend-container -p 5000:5000 \
          -e DB_NAME=cruddb \
          -e DB_USER=cruduser \
          -e DB_PASSWORD=password \
          -e DB_HOST=localhost \
          git-backend
    - name: Check if container is running
      run: docker ps -a | grep git-backend-container || echo "Container not found"

    - name: Wait and test Flask endpoint
      run: |
        docker ps
        sleep 10  # wait for Flask to start
        docker ps
        curl http://localhost:5000
        sleep 5
        docker logs git-backend-container

